Resources:
  MyInstance:
    Type: AWS::EC2::Instance 
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0440d3b780d96b29d
      Tags:
        - Key: "Name"
          Value: !Join ["_", [my, inst, from, cloudformation]]
      SecurityGroups:
        - !Ref VprofileSG

  VprofileSG:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow ssh & http from MyIP
     SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
 
